import type { Metadata } from 'next';

import './globals.css';
import { bodyFont, headingFont, monoFont } from '@/config';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${bodyFont.variable} ${headingFont.variable} ${monoFont.variable} font-sans`}
      >
        {children}
      </body>
    </html>
  );
}
